{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProject | quote }}
      {{- if .Values.externalSecrets.gcpCredentialsSecret }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.gcpCredentialsSecret.name }}
            key: {{ .Values.externalSecrets.gcpCredentialsSecret.key }}
            namespace: {{ .Values.externalSecrets.gcpCredentialsSecret.namespace }}
      {{- end }}
{{- end }}
