{{- if .Values.searxng.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui-stack.searxng.fullname" . }}
  labels:
    {{- include "open-webui-stack.searxng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.searxng.service.type }}
  ports:
    - port: {{ .Values.searxng.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "open-webui-stack.searxng.selectorLabels" . | nindent 4 }}
{{- end }}
