{{- if .Values.reranker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui-stack.reranker.fullname" . }}
  labels:
    {{- include "open-webui-stack.reranker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reranker.service.type }}
  ports:
    - port: {{ .Values.reranker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "open-webui-stack.reranker.selectorLabels" . | nindent 4 }}
{{- end }}
